# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

if development?
  set :database, {
  adapter: "sqlite3",
  database: "db/db.sqlite3"
  }
else
  set :database, ENV['postgres://putkicdlpifbix:XqseswnxgX6Cqp4kgCVJiaheSn@ec2-107-20-159-155.compute-1.amazonaws.com:5432/d61i492j4ilr7s']
end




